name: Code Formatting

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        submodules: true
    - name: Install .NET Core
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
      with:
        dotnet-version: 10.x
    - name: Install ReSharper
      run: |
        cd csharp
        dotnet tool install -g JetBrains.ReSharper.GlobalTools --version 2025.3.2

    - name: Restore
      run: |
        cd csharp
        dotnet restore ArmoniK.Utils.sln

    - name: Reformat
      run: |
        cd csharp
        jb cleanupcode --profile="Full Cleanup With Headers" ArmoniK.Utils.sln

    - name: Check Diff
      id: check-diff
      run: |
        cd csharp
        DIFF="$(git diff --name-only)"

        if [ -z "$DIFF" ]; then
          echo "OK: Format is clean"
        else
          echo "Error: Format was not clean"
          echo "List of files:"
          echo "$DIFF"
          git diff
          exit 1
        fi
    - name: Generate patch
      if: ${{ failure() && steps.check-diff.conclusion == 'failure' }}
      run: |
        git diff > patch-csharp.diff
    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      if: ${{ failure() && steps.check-diff.conclusion == 'failure' }}
      with:
        name: patch-csharp
        path: ./patch-csharp.diff
