name: Deploy

on:
  push:
    branches: [ '**' ]

jobs:


 versionning:
    name: Versionning
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.genver.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Generate Version
      id: genver
      run: |
        VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version /bin/git-version --folder=/repo --release-branch=${{ github.ref_name }}-pre --dev-branch=main)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "VERSION : $VERSION"
        echo "Version :" >> $GITHUB_STEP_SUMMARY
        echo "$VERSION" >> $GITHUB_STEP_SUMMARY

 build:
    runs-on: ubuntu-latest
    needs:
      - versionning
    env:
      GENVERSION: ${{ needs.versionning.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        submodules: true
    - name: Install .NET Core
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: 9.x

    - name: Build the package
      working-directory: csharp
      run: |
         dotnet build ArmoniK.Utils.sln -c Release

    - name: Pack the package VERSION
      working-directory: csharp
      run: |
        dotnet pack ArmoniK.Utils.sln -c Release -o /tmp/packages -p:Version=$GENVERSION

    - name: Push the package
      working-directory: csharp
      run: |
        dotnet nuget push /tmp/packages/ArmoniK.Utils.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols

 test:
    needs:
      - build

    strategy:
      matrix:
        dotnet:
          - version: ""
            framework: "net4.7"
          - version: ""
            framework: "net4.8"
          - version: "6.0"
            framework: "net6.0"
          - version: "7.0"
            framework: "net7.0"
          - version: "8.0"
            framework: "net8.0"
          - version: "9.0"
            framework: "net9.0"
        platform:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: windows-latest
            runtime: windows-x64
        exclude:
          - dotnet:
              version: ""
              framework: "net4.7"
            platform:
              os: ubuntu-latest
              runtime: linux-x64
          - dotnet:
              version: ""
              framework: "net4.8"
            platform:
              os: ubuntu-latest
              runtime: linux-x64
      fail-fast: false
    runs-on: ${{ matrix.platform.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Install .NET Core
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      if: ${{ matrix.dotnet.version }} != ""
      with:
        dotnet-version: |
          ${{ matrix.dotnet.version }}
          9.x

    - name: Run tests
      working-directory: csharp
      run: |
        dotnet test -filter "FullyQualifiedName!~ArmoniK.Utils.DocExtractor" --runtime ${{ matrix.platform.runtime }} -f ${{ matrix.dotnet.framework }} --logger "trx;LogFileName=test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2
      if: always()
      with:
        name: IntegrationTests ${{ matrix.platform.runtime }} ${{ matrix.dotnet.framework }}
        path: ./csharp/tests/TestResults/test-results.trx
        reporter: dotnet-trx
extract-doc:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Install .NET Core
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: "8.0"

    - name: Run tests
      working-directory: csharp
      run: |
        dotnet test --filter "FullyQualifiedName=ArmoniK.Utils.DocExtractor" --runtime linux-x64 -f net8.0 --logger "trx;LogFileName=test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2
      if: always()
      with:
        name: IntegrationTests linux-x64 net8.0
        path: ./csharp/tests/TestResults/test-results.trx
        reporter: dotnet-trx