name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
 versionning:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.target_commitish == 'main' }} 
    outputs:
      version: ${{ steps.snapshot.outputs.version }}
      release: ${{ steps.release.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Remove tag locally
      run: |
        echo  ${{ github.head_ref }}
        git tag -d ${{ github.ref_name }}
